// Code generated by mockery v2.8.0. DO NOT EDIT.

// +build test

package mocks

import (
	alice "github.com/azzzak/alice"

	mock "github.com/stretchr/testify/mock"
)

// aliceAPI is an autogenerated mock type for the aliceAPI type
type aliceAPI struct {
	mock.Mock
}

// ListenForWebhook provides a mock function with given fields: addr, opts
func (_m *aliceAPI) ListenForWebhook(addr string, opts ...func(*alice.Options)) alice.Stream {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, addr)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	var r0 alice.Stream
	if rf, ok := ret.Get(0).(func(string, ...func(*alice.Options)) alice.Stream); ok {
		r0 = rf(addr, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(alice.Stream)
		}
	}

	return r0
}
