// Code generated by mockery v2.8.0. DO NOT EDIT.

// +build test

package mocks

import (
	context "context"
	api "tourist-alice-skill/internal/api"

	mock "github.com/stretchr/testify/mock"

	primitive "go.mongodb.org/mongo-driver/bson/primitive"
)

// ChatStateService is an autogenerated mock type for the ChatStateService type
type ChatStateService struct {
	mock.Mock
}

// DeleteById provides a mock function with given fields: ctx, id
func (_m *ChatStateService) DeleteById(ctx context.Context, id primitive.ObjectID) error {
	ret := _m.Called(ctx, id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, primitive.ObjectID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Save provides a mock function with given fields: ctx, u
func (_m *ChatStateService) Save(ctx context.Context, u *api.ChatState) error {
	ret := _m.Called(ctx, u)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *api.ChatState) error); ok {
		r0 = rf(ctx, u)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
