// Code generated by mockery v2.8.0. DO NOT EDIT.

// +build test

package mocks

import (
	api "tourist-alice-skill/internal/api"

	alice "github.com/azzzak/alice"

	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Interface is an autogenerated mock type for the Interface type
type Interface struct {
	mock.Mock
}

// HasReact provides a mock function with given fields: update
func (_m *Interface) HasReact(update api.Update) bool {
	ret := _m.Called(update)

	var r0 bool
	if rf, ok := ret.Get(0).(func(api.Update) bool); ok {
		r0 = rf(update)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// OnMessage provides a mock function with given fields: ctx, update
func (_m *Interface) OnMessage(ctx context.Context, update api.Update) (*alice.Response, error) {
	ret := _m.Called(ctx, update)

	var r0 *alice.Response
	if rf, ok := ret.Get(0).(func(context.Context, api.Update) *alice.Response); ok {
		r0 = rf(ctx, update)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*alice.Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, api.Update) error); ok {
		r1 = rf(ctx, update)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
