// Code generated by mockery v2.8.0. DO NOT EDIT.

// +build test

package mocks

import (
	context "context"
	api "tourist-alice-skill/internal/api"

	mock "github.com/stretchr/testify/mock"
)

// UserService is an autogenerated mock type for the UserService type
type UserService struct {
	mock.Mock
}

// FindById provides a mock function with given fields: ctx, id
func (_m *UserService) FindById(ctx context.Context, id int) (*api.User, error) {
	ret := _m.Called(ctx, id)

	var r0 *api.User
	if rf, ok := ret.Get(0).(func(context.Context, int) *api.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*api.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
