name: Check labels

on:
  pull_request:
    types: [ labeled, unlabeled, ready_for_review, synchronize ]
  pull_request_review:
    types: [ submitted ]

jobs:
  check-labels:
    name: Check labeles
    runs-on: ubuntu-18.04
    steps:
      - name: Check lables
        uses: zwaldowski/match-label-action@v2
        with:
          allowed: 'type:fix, type:features, type:documentation, type:tests, type:config'

