name: Opened pr checker

on:
  pull_request:
    types: [ opened, reopened ]

jobs:
  pr-analyze:
    name: Analyze pr
    runs-on: ubuntu-latest
    steps:
      - name: Add issue link
        uses: tkt-actions/add-issue-links@v1.4.0
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          branch-prefix: '/'
      - name: Assign PullRequest to Project
        uses: technote-space/create-project-card-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          PROJECT: Tourist-feature-tracker
          COLUMN: In progress
          CHECK_ORG_PROJECT: true
      - name: Assign Author as Assignee
        uses: toshimaru/auto-author-assign@v1.3.4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}